apiVersion: v1
kind: Service
metadata:
  name: kafka-local
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-local
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 9092
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: zoo-local
#spec:
#  ports:
#    - protocol: TCP
#      port: 2181
#      targetPort: 2181
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: zoo-local
#subsets:
#  - addresses:
#      - ip: 10.0.2.2
#    ports:
#      - port: 2181
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: schema-local
#spec:
#  ports:
#    - protocol: TCP
#      port: 8081
#      targetPort: 8081
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: schema-local
#subsets:
#  - addresses:
#      - ip: 10.0.2.2
#    ports:
#      - port: 8081
