apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-app-config
  namespace: default
data:
  WORK_DATE_TIME: '2021-06-18T19:05:00'
  IGNITE_NAMESPACE: 'ignite'
  IGNITE_SERVICE_NAME: 'ignite-cluster'
  IGNITE_MASTER_URL: 'https://kubernetes.default.svc.cluster.local:443'
  IGNITE_CACHE_NAME: 'images-cache'
---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-app
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "docker.io/shipa/spark:latest"
  imagePullPolicy: Always
  mainClass: ru.shipa.image.processing.ImageProcessingApp
  mainApplicationFile: "local:///opt/spark/image-processing-1.0-SNAPSHOT-all.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark-with-ignite
    envFrom:
      - configMapRef:
          name: spark-app-config
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    envFrom:
      - configMapRef:
          name: spark-app-config
