apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite
  namespace: ignite-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ignite-role
  namespace: ignite-server
rules:
  - apiGroups:
      - ""
    resources: # Here are resources you can access
      - pods
      - endpoints
    verbs: # That is what you can do with them
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ignite-role-binding
  namespace: ignite-server
subjects:
  - kind: ServiceAccount
    name: ignite
    namespace: ignite-server
roleRef:
  kind: ClusterRole
  name: ignite-role
  apiGroup: rbac.authorization.k8s.io
