apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite-cluster-account
  namespace: ignite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ignite-cluster-role
  namespace: ignite
rules:
  - apiGroups:
      - ""
    resources: # Here are the resources you can access
      - pods
      - endpoints
    verbs: # That is what you can do with them
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ignite-cluster-role-binding
  namespace: ignite
subjects:
  - kind: ServiceAccount
    name: ignite-cluster-account
    namespace: ignite
roleRef:
  kind: ClusterRole
  name: ignite-cluster-role
  apiGroup: rbac.authorization.k8s.io
