apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-with-ignite
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-with-ignite-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - endpoints
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-with-ignite-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: spark-with-ignite
    namespace: default
roleRef:
  kind: ClusterRole
  name: spark-with-ignite-role
  apiGroup: rbac.authorization.k8s.io
