apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ignite-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ignite-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ignite
    namespace: default
roleRef:
  kind: ClusterRole
  name: ignite-role
  apiGroup: rbac.authorization.k8s.io
