apiVersion: v1
kind: ConfigMap
metadata:
  name: ignite-service-config
  namespace: ignite-client
data:
  IGNITE_KUBER_MODE: 'true'
  IGNITE_SERVICE_NAME: 'ignite-app'
  IGNITE_NAMESPACE: 'ignite-client'
  IGNITE_MASTER_URL: 'https://ignite-service.ignite-server.svc.cluster.local:443'
  IGNITE_CACHE_NAME: 'images-cache'
  KAFKA_BOOTSTRAP_SERVERS_IP: '127.0.0.1:9092'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-app-service
  namespace: ignite-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignite-cache
  template:
    metadata:
      labels:
        app: ignite-cache
    spec:
      serviceAccountName: ignite-app
      containers:
        - name: ignite-app-container
          image: "docker.io/shipa/ignite-persistence:latest"
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
            limits:
              memory: "700Mi"
              cpu: "500m"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ignite-service-config
          ports:
            - name: http
              containerPort: 8080 # REST API
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ignite-app
  namespace: ignite-client
spec:
  type: NodePort
  selector:
    app: ignite-cache
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31007
