apiVersion: v1
kind: ConfigMap
metadata:
  name: ignite-service-config
  namespace: default
data:
  IGNITE_KUBER_MODE: 'true'
  IGNITE_SERVICE_NAME: 'ignite'
  IGNITE_NAMESPACE: 'default'
  IGNITE_MASTER_URL: 'https://192.168.64.4:8443'
  IGNITE_CACHE_NAME: 'images-cache'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: ignite-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: ignite-cache
    spec:
      serviceAccountName: ignite
      containers:
        - name: ignite-service-container
          image: "docker.io/mmrovnyagin/test-service:lab5"
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
            limits:
              memory: "700Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ignite-service-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ignite
  namespace: default
spec:
  type: NodePort
  selector:
    app: ignite-cache
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31007
