all:
  hosts:
    node1:
      ansible_host: 192.168.12.65
      ip: 192.168.12.65
      access_ip: 192.168.12.65
    node2:
      ansible_host: 192.168.12.66
      ip: 192.168.12.66
      access_ip: 192.168.12.66
    node3:
      ansible_host: 192.168.12.67
      ip: 192.168.12.67
      access_ip: 192.168.12.67
  children:
    kube-master:
      hosts:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
